spring:
  application:
    name: ProducerService
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    username: ${USERNAME}
    password: ${PASSWORD}
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
  kafka:
    bootstrap-servers: localhost:29092

server:
  port: 666

client:
  topics:
    order: order.v1